--A10B B--

ALTER PROCEDURE populate_DB
AS BEGIN

ALTER TABLE FACT
DROP CONSTRAINT PK_COMPOSITEID,
constraint FK_PRODUCTID,
constraint fk_timeid,
constraint FK_CUSTOMERID,
constraint fk_employeeid

alter table productdim
drop constraint pk_productid
alter table timedim
drop constraint pk_timeid
alter table customerdim
drop constraint pk_customerid
alter table employeedim
drop constraint pk_employeeid

truncate table fact
truncate table productdim
truncate table employeedim
truncate table timedim
truncate table customerdim
truncate table staging


Alter Table PRODUCTDIM ADD CONSTRAINT PK_PRODUCTID PRIMARY KEY (PRODUCTID)
ALTER TABLE TIMEDIM ADD CONSTRAINT PK_TIMEID PRIMARY KEY (TIMEID)
ALTER TABLE CUSTOMERDIM ADD CONSTRAINT PK_CUSTOMERID PRIMARY KEY (CUSTOMERID)
ALTER TABLE EMPLOYEEDIM ADD CONSTRAINT PK_EMPLOYEEID PRIMARY KEY (EMPLOYEEID)
ALTER TABLE FACT ADD CONSTRAINT FK_PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTDIM(PRODUCTID)
ALTER TABLE FACT ADD CONSTRAINT FK_TIMEID FOREIGN KEY (TIMEID) REFERENCES TIMEDIM(TIMEID)
ALTER TABLE FACT ADD CONSTRAINT FK_CUSTOMERID FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERDIM(CUSTOMERID)
ALTER TABLE FACT ADD CONSTRAINT FK_EMPLOYEEID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEDIM(EMPLOYEEID)

INSERT INTO CUSTOMERDIM
SELECT CUST_CODE, CUST_FNAME, CUST_LNAME, CUST_CITY, CUST_STATE, CUST_ZIP
FROM LGCUSTOMER

INSERT INTO EMPLOYEEDIM
SELECT E.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME, E.EMP_TITLE,D.DEPT_NUM, D.DEPT_NAME
FROM LGEMPLOYEE E INNER JOIN LGDEPARTMENT D ON E.DEPT_NUM = D.DEPT_NUM

INSERT INTO TIMEDIM
SELECT INV_DATE, YEAR(INV_DATE), MONTH(INV_DATE), DATEPART(QUARTER,INV_DATE)
FROM lginvoice 

INSERT INTO PRODUCTDIM
SELECT P.PROD_SKU, P.PROD_DESCRIPT, P.PROD_TYPE, B.BRAND_ID, B.BRAND_NAME
FROM LGPRODUCT P INNER JOIN LGBRAND B ON P.BRAND_ID = B.BRAND_ID

INSERT INTO STAGING (PROD_SKU, CUST_CODE, INV_DATE, EMP_NUM, LINE_QTY, LINE_PRICE) 
SELECT PROD_SKU, CUST_CODE, INV_DATE, I.EMPLOYEE_ID AS EMP_NUM, SUM(LINE_QTY) AS LINE_QTY, AVG(LINE_PRICE)
FROM LGINVOICE I INNER JOIN LGLINE L ON I.INV_NUM = L.INV_NUM
GROUP BY PROD_SKU, CUST_CODE, INV_DATE, EMPLOYEE_ID

UPDATE STAGING
SET CUSTOMERID = C.CUSTOMERID
FROM STAGING S INNER JOIN CUSTOMERDIM C ON S.CUST_CODE = C.CUST_CODE

UPDATE STAGING
SET PRODUCTID = P.PRODUCTID
FROM STAGING S INNER JOIN PRODUCTDIM P ON S.PROD_SKU = P.PROD_SKU

UPDATE STAGING
SET TIMEID = T.TIMEID
FROM STAGING S INNER JOIN TIMEDIM T ON S.INV_DATE = T.INV_DATE

UPDATE STAGING
SET EMPLOYEEID = E.EMPLOYEEID
FROM STAGING S INNER JOIN EMPLOYEEDIM E ON S.EMP_NUM = E.EMP_NUM

INSERT INTO FACT
SELECT S.PRODUCTID, S.TIMEID, S.CUSTOMERID, S.EMPLOYEEID, LINE_QTY, LINE_PRICE
FROM STAGING S
GROUP BY PRODUCTID, TIMEID, CUSTOMERID, EMPLOYEEID, LINE_QTY, LINE_PRICE

END
EXEC POPULATE_DB




