--A10B A--

CREATE Table PRODUCTDIM(
PRODUCTID INT IDENTITY NOT NULL,
PROD_SKU VARCHAR(30),
PROD_DESCRIPT VARCHAR(140),
PROD_TYPE VARCHAR(11), BRAND_ID INT,
BRAND_NAME VARCHAR(20));

CREATE Table TIMEDIM(
TIMEID INT IDENTITY NOT NULL,
INV_DATE DATE, YEAR INT, MONTH INT, QUARTER INT);

CREATE Table CUSTOMERDIM(
CUSTOMERID INT IDENTITY NOT NULL,
CUST_CODE NUMERIC NOT NULL,
CUST_FNAME VARCHAR(20), CUST_LNAME VARCHAR(20),
CUST_CITY VARCHAR(50), CUST_STATE CHAR(2), CUST_ZIP CHAR(5));

CREATE Table EMPLOYEEDIM(
EMPLOYEEID INT IDENTITY NOT NULL, EMP_NUM INT,
EMP_FNAME VARCHAR(20), EMP_LNAME VARCHAR(20),
EMP_TITLE VARCHAR(30), DEPT_NUM INT, DEPT_NAME VARCHAR(30));

CREATE Table FACT(
PRODUCTID INT NOT NULL, TIMEID INT NOT NULL,
CUSTOMERID INT NOT NULL, EMPLOYEEID INT NOT NULL, 
LINE_QTY INT, LINE_PRICE FLOAT);

Alter Table PRODUCTDIM ADD CONSTRAINT PK_PRODUCTID PRIMARY KEY (PRODUCTID);
ALTER TABLE TIMEDIM ADD CONSTRAINT PK_TIMEID PRIMARY KEY (TIMEID);
ALTER TABLE CUSTOMERDIM ADD CONSTRAINT PK_CUSTOMERID PRIMARY KEY (CUSTOMERID);
ALTER TABLE EMPLOYEEDIM ADD CONSTRAINT PK_EMPLOYEEID PRIMARY KEY (EMPLOYEEID);
ALTER TABLE FACT ADD CONSTRAINT PK_COMPOSITEID PRIMARY KEY (PRODUCTID,TIMEID,CUSTOMERID,EMPLOYEEID)
ALTER TABLE FACT ADD CONSTRAINT FK_PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTDIM(PRODUCTID);
ALTER TABLE FACT ADD CONSTRAINT FK_TIMEID FOREIGN KEY (TIMEID) REFERENCES TIMEDIM(TIMEID);
ALTER TABLE FACT ADD CONSTRAINT FK_CUSTOMERID FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERDIM(CUSTOMERID);
ALTER TABLE FACT ADD CONSTRAINT FK_EMPLOYEEID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEDIM(EMPLOYEEID);


CREATE TABLE Staging(
PROD_SKU VARCHAR(30),
CUST_CODE INT,
INV_DATE DATE,
EMP_NUM INT,
LINE_QTY INT,
LINE_PRICE FLOAT,
PRODUCTID INT,
TIMEID INT,
CUSTOMERID INT,
EMPLOYEEID INT)
