--4
SELECT TOP 5 SUM(LINE_QTY * LINE_PRICE) AS SALES, P.PROD_SKU
FROM FACT F INNER JOIN PRODUCTDIM P ON F.PRODUCTID = P.PRODUCTID
GROUP BY P.PROD_SKU
ORDER BY SALES 

--5
SELECT DISTINCT E.EMP_FNAME, E.EMP_LNAME, SUM(LINE_QTY * LINE_PRICE) AS SALES
FROM EMPLOYEEDIM E INNER JOIN FACT F ON E.EMPLOYEEID = F.EMPLOYEEID
GROUP BY E.EMP_FNAME, E.EMP_LNAME
ORDER BY EMP_FNAME, EMP_LNAME